name: atomic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  file_picker: ^6.1.1
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  open_filex: ^4.3.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sizer: ^3.0.0
  text_scroll: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

